OUTPUT_PATH: '/home/sherry/output/ucf'

TRAIN:
    DATASET: "ucf101"

DATASET:
    VID_PATH: '/media/diskstation/datasets/UCF101/jpg'
    ANNOTATION_PATH: '/media/diskstation/datasets/UCF101/json/ucf101_01.json'
    CLUSTER_PATH: '/media/diskstation/datasets/UCF101/vid_clusters.txt'

    TARGET_TYPE_T: 'cluster_label'
    TARGET_TYPE_V: 'label'

    SAMPLING_STRATEGY: 'random_semi_hard'
    POSITIVE_SAMPLING_P: 0.2

MODEL:
    ARCH: 'uber_nce' #'3dresnet'

RESNET:
    MODEL_DEPTH: 18
    N_CLASSES: 101
    PROJECTION_HEAD: True
    HIDDEN_LAYER: 2048
    OUT_DIM: 128
    
    SHORTCUT: 'B'
    CONV1_T_SIZE: 7
    CONV1_T_STRIDE: 1
    NO_MAX_POOl: true
    WIDEN_FACTOR: 1

DATA:
    SAMPLE_SIZE: 128 #128
    SAMPLE_DURATION: 16
    INPUT_CHANNEL_NUM: 3

LOSS:
    MARGIN: 0.2
    FEAT_DIM: 128
    # K: 1024 #num of negatives
    # T: 0.07
    # M: 0.5

OPTIM:
    LR: 0.001 #0.01
    SCHEDULE: [120, 160]
    MOMENTUM: 0.5
    