TRAIN:
    DATASET: "hmdb51"

DATASET:
    VID_PATH: '/media/synology/datasets/HMDB51/jpg'
    ANNOTATION_PATH: '/media/synology/datasets/HMDB51/json/hmdb51_1.json'

    TARGET_TYPE_T: 'cluster_label'
    TARGET_TYPE_V: 'label'

    SAMPLING_STRATEGY: 'random_semi_hard'
    POSITIVE_SAMPLING_P: 0.2

MODEL:
    ARCH: '3dresnet'

RESNET:
    MODEL_DEPTH: 18
    N_CLASSES: 2048 #512
    # N_INPUT_CHANNELS: 3
    SHORTCUT: 'B'
    CONV1_T_SIZE: 7
    CONV1_T_STRIDE: 1
    NO_MAX_POOl: true
    WIDEN_FACTOR: 1

DATA:
    SAMPLE_SIZE: 128
    SAMPLE_DURATION: 16
    INPUT_CHANNEL_NUM: 3

LOSS:
    MARGIN: 0.2

OPTIM:
    LR: 0.1
    MOMENTUM: 0.5
