TRAIN:
    DATASET: "ucf101"

DATASET:
    VID_PATH: '/media/diskstation/datasets/UCF101/jpg'
    ANNOTATION_PATH: '/media/diskstation/datasets/UCF101/UCF101_Flow/json/ucf101_01.json' #optical flow
    # CLUSTER_PATH: '/media/diskstation/datasets/UCF101/vid_clusters.txt' #EDIT DELETE THIS!x

    TARGET_TYPE_T: 'cluster_label'
    TARGET_TYPE_V: 'label'

    # SAMPLING_STRATEGY: 'random_semi_hard'
    SAMPLING_STRATEGY: 'noise_contrastive'
    POSITIVE_SAMPLING_P: 0.2

    POS_CHANNEL_REPLACE: True
    PROB_POS_CHANNEL_REPLACE: 0.25

    CHANNEL_EXTENSIONS: 'optical_u'
    OPTICAL_U_PATH: /media/diskstation/datasets/UCF101/UCF101_Flow/tvl1_flow/u

MODEL:
    ARCH: '3dresnet'

ITERCLUSTER:
    METHOD: 'finch'

RESNET:
    MODEL_DEPTH: 18
    N_CLASSES: 2048 #512
    # N_INPUT_CHANNELS: 3
    SHORTCUT: 'B'
    CONV1_T_SIZE: 7
    CONV1_T_STRIDE: 1
    NO_MAX_POOl: true
    WIDEN_FACTOR: 1

DATA:
    SAMPLE_SIZE: 128
    SAMPLE_DURATION: 32
    INPUT_CHANNEL_NUM: 3

LOSS:
    MARGIN: 0.2
    LOCAL_LOCAL_CONTRAST: True

OPTIM:
    LR: 0.1
    MOMENTUM: 0.5
