TRAIN:
    DATASET: kinetics
    BATCH_SIZE: 8
    NUM_DATA_WORKERS: 4

DATASET:
    VID_PATH: .
    ANNOTATION_PATH: /home/salar77h/projects/def-florian7/datasets/kinetics400/vid_paths_and_labels/frame_paths
    CLUSTER_PATH: '/home/salar77h/projects/def-florian7/datasets/kinetics400/vid_clusters.txt'
    TARGET_TYPE_T: 'cluster_label'
    TARGET_TYPE_V: 'label'
    POSITIVE_SAMPLING_P: 0.8

MODEL:
    ARCH: slowfast

DATA:
    SAMPLE_DURATION: 16
    SAMPLE_SIZE: 128
    INPUT_CHANNEL_NUM: 3
    
SLOWFAST:
    CFG_PATH: /home/salar77h/projects/def-florian7/salar77h/repos/video_similarity_search/models/slowfast/configs/Kinetics/SLOWFAST_8x8_R50.yaml

OUTPUT_PATH: /home/salar77h/projects/def-florian7/salar77h/repos/video_similarity_search/output_kinetics 
