TRAIN:
    DATASET: ucf101
    BATCH_SIZE: 8

DATASET:
    VID_PATH: ./jpg
    ANNOTATION_PATH: /home/salar77h/projects/def-florian7/datasets/UCF101/json/ucf101_01.json

MODEL:
    ARCH: slowfast

DATA:
    SAMPLE_DURATION: 32
    SAMPLE_SIZE: 128
    
SLOWFAST:
    CFG_PATH: /home/salar77h/projects/def-florian7/salar77h/repos/video_similarity_search/models/slowfast/configs/Kinetics/SLOWFAST_8x8_R50.yaml

OUTPUT_PATH: /home/salar77h/projects/def-florian7/salar77h/repos/video_similarity_search 
