TRAIN:
    DATASET: ucf101
    BATCH_SIZE: 16
    NUM_DATA_WORKERS: 4

DATASET:
    VID_PATH: /media/diskstation/datasets/UCF101/jpg
    ANNOTATION_PATH: /media/diskstation/datasets/UCF101/json/ucf101_01.json

MODEL:
    ARCH: slowfast

DATA:
    SAMPLE_DURATION: 32
    SAMPLE_SIZE: 128
    


